### ISSUE TITLE
Add flatten

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/pyramda#3]

**Comment by skabbass1** [comment]
Please assign to me

**Comment by skabbass1** [comment]
@jackfirth I noticed that Ramda does not have a flatten_once function. It just has a general purpose flatten method. Is there a reason you  want to implement  flatten_once instead of flatten? I presume  the intent of flatten_once is to not flatten nested lists within a list?

**Comment by jackfirth** [comment]
I don't remember my thinking when I opened this issue honestly. I suspect it had something to do with the fact that Python strings are considered sequences of one-character strings, so a naive approach to implementing `flatten` will loop forever.

**Comment by skabbass1** [comment]
I created a flatten function which takes a depth argument to control the traversal depth while flattening a sequence. I also put in some checks in place to avoid recursing infinitely when strings are part of the sequence.
