### ISSUE TITLE
Drop Python 2.x support entirely

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/pyramda#35]
Pyramda tries to support both Python 2 and 3 in a clever way: it uses `pasteurize` in [`setup.py`][setup] to rewrite the code to be compatible with python 2 while it's being installed. This is a horrible idea and it causes all sorts of problems, like #8 and #28.

Python 2 is being retired globally [starting in 2020][python-countdown], so there's not much point to supporting it anymore. Deleting the `pasteurize` nonsense entirely from `setup.py` would be a great thing for somebody to do. I doubt I'll get around to it myself, since I don't work in Python professionally anymore.

[python-countdown]: https://pythonclock.org
[setup]: https://github.com/jackfirth/pyramda/blob/master/setup.py

**Comment by vgangaprasad** [comment]
Hello Jack,

I made the changes to setup.py and .travis.yml and pushed it, Could you please check if it looks fine and merge it.

Build for 3.3 version fails in Travis and it looks like a known issue, i can remove 3.3 from Travis.yml if that is OK with you.


Thanks,
Vijay

**Comment by jackfirth** [comment]
@vgangaprasad Thank you! I left a few comments on the pull request. Once those are resolved I will very happily merge it.

**Comment by jackfirth** [comment]
Closed by #36 (hooray!)
